"""empty message

Revision ID: 5de8dd65b29f
Revises: a3aa031bd0da
Create Date: 2024-08-28 12:05:07.359958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de8dd65b29f'
down_revision = 'a3aa031bd0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_path', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('save_path')

    # ### end Alembic commands ###
